### DISCUSSION TITLE
How to create a docker that runs ghorg periodically?

### DISCUSSION THREAD

**Discussion by phatpaul** [gabrie30/ghorg#390] [Q&A] [answered]
My use case:
I want a service to run periodically and scan my Gitlab instance for any changes to repositories and update a local copy of all repos.  I would like to set up a docker-compose.yml file and start it and forget about it.  (I realize this isn't the most efficient use of bandwidth, but at-least I'm using self-hosted servers.)

I'm thinking something like this docker-compose.yml:
```yml 
version: '3.6'

# note: create a text file named .env in the same dir as this file with contents:
#GHORG_GITLAB_TOKEN=xxxxx

services:
  repos-ro-mirror:
    image: ghcr.io/gabrie30/ghorg:v1.9.10
    restart: unless-stopped
    environment:
    - GHORG_GITLAB_TOKEN
    volumes:
    - ./config:/config
    - ./repos:/data
    # command to execute
    command: "/bin/sh -c 'while :; do ghorg reclone; sleep 10m & wait $${!}; done'"
    entrypoint: ""
```
and my list of things to clone in reclone.yaml:
```yml
# Example for gitlab; update with your gitlab cloud token
my-gitlab:
  cmd: "ghorg clone mygroup --scm=gitlab --fetch-all --base-url=https://gitlab.myserver.com"
```

Am I going about this the best way?  Thanks!
